### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by vpanjganj** [sonnylazuardi/21mobile#1] opened 2016-09-21 10:05 UTC
I tried to run `react-native run-ios` after installing node dependencies but my build failed:

```
=== BUILD TARGET React OF PROJECT React WITH CONFIGURATION Debug ===
Check dependencies

** BUILD FAILED **


The following build commands failed:
    Ld build/Build/Intermediates/blitzmobile.build/Debug-iphonesimulator/blitzmobile.build/Objects-normal/x86_64/blitzmobile normal x86_64
    Ld build/Build/Intermediates/blitzmobile.build/Debug-iphonesimulator/blitzmobile.build/Objects-normal/i386/blitzmobile normal i386
(2 failures)
```

**Comment by sonnylazuardi** [comment] 2016-09-21 15:40
@vpanjganj have you tried running from xcode?

**Comment by poindexd** [comment] 2016-09-24 05:10
Build failed for me as well, fixed by: Target > Build Settings > Build Active Architecture Only > Debug > Yes

**Comment by lwinkyawmyat** [comment] 2016-09-24 10:17
I'm also have the same issue on building on android 6.0.1

**Comment by sonnylazuardi** [comment] 2016-09-25 02:28
I think the issue is closed

**Closed as completed by sonnylazuardi** 2016-09-25 02:28 UTC
